# Generated by Django 3.1.4 on 2020-12-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0004_auto_20201218_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
