# Generated by Django 3.1.4 on 2020-12-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0007_auto_20201219_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='django',
            name='image',
        ),
        migrations.RemoveField(
            model_name='python',
            name='image',
        ),
    ]
