# Generated by Django 3.1.4 on 2020-12-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Application', '0008_auto_20201219_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datascience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=20)),
                ('text4', models.TextField()),
            ],
        ),
    ]
